---
title: "Performance scatterplots"
output: html_notebook
---

# Setup

```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = file.path(getwd(), '..'))
```

```{r libraries, echo=FALSE}
library(here) 
library(phyloseq) 
library(tidyverse) 
```

# Read in data

## Metabarcoding performance metrics

```{r}
# trnL only
# 1-2 days' prior menu, >4 counts per taxon
pred.mb <- 
     here('data', 
          'processed',
          'performance-metrics',
          # '20210913_Metabarcoding v. menu predictions by family, 1-2d prior, >4 counts per taxon filter, no intake filter.rds') %>%
          '20210913_Metabarcoding v. menu predictions by genus, 1-2d prior, >4 counts per taxon filter, no intake filter.rds') %>%
     readRDS()
```

## Metaproteomic performance metrics

```{r}
# Protein unique peptides
pred.mp.pup <- 
     here('data', 
          'processed', 
          'performance-metrics',
          # '20210913_Metaproteomic v. menu predictions by food family, 1-2d prior, >4 counts per taxon filter, no intake filter, v2 analysis.rds') %>%
          '20210913_Metaproteomic v. menu predictions by food genus, 1-2d prior, >4 counts per taxon filter, no intake filter, v2 analysis.rds') %>% 
     readRDS()
```

```{r}
# Unique peptides
pred.mp.up <- 
     here('data', 
          'processed',
          'performance-metrics',
          # '20210912_Metaproteomic v. menu predictions by food family, 1-2d prior, >4 counts per taxon filter, v3 analysis.rds') %>%
          '20210912_Metaproteomic v. menu predictions by food genus, 1-2d prior, >4 counts per taxon filter, no intake filter, v3 analysis.rds') %>% 
     readRDS()
```

# Pre-process

```{r}
# Annotate each dataset prior to joining
pred.mb$detection <- 'DNA'
pred.mp.pup$detection <- 'Protein (1PUP)'
pred.mp.up$detection <- 'Protein (1UP)'

# Get shared variables
vs <- 
     intersect(names(pred.mb), names(pred.mp.up)) %>% 
     intersect(names(pred.mp.pup))

# Just concatenate end to end for now
pred <- 
     bind_rows(select(pred.mb, one_of(vs)),
               select(pred.mp.pup, one_of(vs)),
               select(pred.mp.up, one_of(vs))) 

pred
```
## Summarize sensitivity, specificity

```{r}
# Need to shift data to wide form
pred <- pivot_wider(pred, names_from = prediction, values_from = count)
pred
```
```{r}
# Calculate sensitivity, specificity
pred.summary <- 
     pred %>% 
     rename(TP = `True positive`, TN = `True negative`,
            FP = `False positive`, FN = `False negative`) %>% 
     mutate(sensitivity = TP/(TP + FN), 
            specificity = TP/(TP + FP))

pred.summary
```
```{r}
# Now split apart by data type, so I can join back together
pred.summary.mb <- 
     filter(pred.summary, detection == 'DNA') %>% 
     rename(sensitivity_DNA = sensitivity,
            specificity_DNA = specificity) %>% 
     select(-(detection:FN))

pred.summary.pup <- 
     filter(pred.summary, detection == 'Protein (1PUP)') %>% 
     rename(sensitivity_pup = sensitivity,
            specificity_pup = specificity) %>% 
     select(-(detection:FN))

pred.summary.up <- 
     filter(pred.summary, detection == 'Protein (1UP)') %>% 
     rename(sensitivity_up = sensitivity,
            specificity_up = specificity) %>% 
     select(-(detection:FN))

# Full join on taxon name
pred.summary <- 
     full_join(pred.summary.mb, pred.summary.pup) %>% 
     full_join(pred.summary.up)

pred.summary
```
# Visualize 

## Metaproteomics alone

```{r}
ggplot(pred.summary.pup, aes(x = 1 - specificity_pup,
                            y = sensitivity_pup)) +
     geom_point(size = 2, alpha = 0.6) +
     coord_equal() +
     labs(x = '1 - Specificity', y = 'Sensitivity') +
     theme_bw()

plotID <- paste(Sys.Date(), as.character(sample(000:999,1)), sep=".")

ggsave(here('results', 'performance metrics', 
            paste0(plotID, '_Metaproteomic ROC analogue.png')),
       height = 5, width = 5)
```

```{r}
ggplot(pred.summary.mb, aes(x = 1 - specificity_DNA,
                            y = sensitivity_DNA)) +
     geom_point(size = 2, alpha = 0.6) +
     coord_equal() +
     labs(x = '1 - Specificity', y = 'Sensitivity') +
     theme_bw()

plotID <- paste(Sys.Date(), as.character(sample(000:999,1)), sep=".")

ggsave(here('results', 'performance metrics', 
            paste0(plotID, '_Metabarcoding ROC analogue.png')),
       height = 5, width = 5)
```
## Combined

```{r}
ggplot(pred.summary, aes(x = sensitivity_DNA, y = sensitivity_pup,
                         label = taxon)) +
     annotate("rect", xmin = 0, xmax = 0.5, ymin = 0, ymax = 0.5, 
              fill= '#FDAE61', alpha = 0.5)  + 
     annotate("rect", xmin = 0.5, xmax = 1, ymin = 0, ymax = 0.5, 
              fill= '#A6D96A', alpha = 0.5)  + 
     annotate("rect", xmin = 0, xmax = 0.5, ymin = 0.5, ymax = 1, 
              fill= '#A6D96A', alpha = 0.5)  + 
     annotate("rect", xmin = 0.5, xmax = 1, ymin = 0.5, ymax = 1, 
              fill= '#1A9641', alpha = 0.5)  +
     geom_point(size = 2, alpha = 0.2) +
     geom_text(hjust = 0, nudge_x = 0.025, nudge_y = 0.01,
               angle = 20, check_overlap = TRUE) +
     coord_equal() +
     scale_x_continuous(breaks = c(0, 0.25, 0.5, 0.75, 1.0),
                        limits = c(0, 1.15)) +
     scale_y_continuous(breaks = c(0, 0.25, 0.5, 0.75, 1.0),
                        limits = c(0, 1.15)) +
     labs(x = 'Metabarcoding sensitivity', y = 'Metaproteomic sensitivity (PUP)') +
     theme_bw()

plotID <- paste(Sys.Date(), as.character(sample(000:999,1)), sep=".")

ggsave(here('results', 'performance metrics', 
            paste0(plotID, '_Sensitivity scatterplot, protein v. DNA compared to menu (genus level).png')),
       height = 5, width = 5)
```

```{r}
ggplot(pred.summary, aes(x = specificity_DNA, y = specificity_pup,
                         label = taxon)) +
     annotate("rect", xmin = 0, xmax = 0.5, ymin = 0, ymax = 0.5, 
              fill= '#FDAE61', alpha = 0.5)  + 
     annotate("rect", xmin = 0.5, xmax = 1, ymin = 0, ymax = 0.5, 
              fill= '#A6D96A', alpha = 0.5)  + 
     annotate("rect", xmin = 0, xmax = 0.5, ymin = 0.5, ymax = 1, 
              fill= '#A6D96A', alpha = 0.5)  + 
     annotate("rect", xmin = 0.5, xmax = 1, ymin = 0.5, ymax = 1, 
              fill= '#1A9641', alpha = 0.5)  +
     geom_point(size = 2, alpha = 0.2) +
     coord_equal() +
     geom_text(hjust = 0, nudge_x = 0.025, nudge_y = 0.01,
               angle = 20, check_overlap = TRUE) +
     coord_equal() +
     scale_x_continuous(breaks = c(0, 0.25, 0.5, 0.75, 1.0),
                        limits = c(0, 1.15)) +
     scale_y_continuous(breaks = c(0, 0.25, 0.5, 0.75, 1.0),
                        limits = c(0, 1.15)) +
     labs(x = 'Metabarcoding specificity', y = 'Metaproteomic specificity (PUP)') +
     theme_bw()

plotID <- paste(Sys.Date(), as.character(sample(000:999,1)), sep=".")

ggsave(here('results', 'performance metrics', 
            paste0(plotID, '_Specificity scatterplot, protein v. DNA compared to menu.png')),
       height = 5, width = 5)
```

## Plot statistics

Pearson correlations between per-taxon metrics
```{r}
# Sensitivity
cor.test(pred.summary$sensitivity_DNA,
         pred.summary$sensitivity_pup,
         alternative = 'two.sided',
         method = 'spearman')
```

```{r}
# Specificity
cor.test(pred.summary$specificity_DNA,
         pred.summary$specificity_pup,
         alternative = 'greater', 
         method = 'spearman')
```

