---
title: "Visualize menu data"
output: html_notebook
---

## Setup

```{r setup}
require(knitr)
knitr::opts_knit$set(root.dir = file.path(getwd(), '..'))
```

```{r}
library(cowplot)
library(ggdendro)
library(here)
library(phyloseq)
library(tidyverse)
```

## Read in data

```{r}
# Tax-glommed
ps.protein <- 
     here('data',
          'processed',
          'phyloseq',
          'combined',
          'filtered',
          'ps_mp_taxa.rds') %>%
     readRDS()

ps.protein
```

```{r}
ps.menu <- 
     here('data', 
          'processed', 
          'phyloseq',
          'combined',
          'filtered',
          'ps_menu.rds') %>% 
     readRDS()

ps.menu
```

## Pre-process

### List samples

ML48 (10/17/19) omitted due to low spectra counts and poor extraction.

```{r}
samdf.protein <- data.frame(ps.protein@sam_data)
samdf.protein
```
```{r}
# Add missing sample
row <- 
     data.frame(subj = 'ML48',
                date = as.Date('2019-10-17'),
                study = 'Intervention',
                time = NA
     ) %>% 
     mutate(delta1 = paste(subj, date-1, sep = '_'),
            delta2 = paste(subj, date-2, sep = '_'))

row
```
```{r}
samdf.protein <- 
     bind_rows(samdf.protein, row) %>% 
     rownames_to_column(var = 'row')
```

### 1-2 days' prior

```{r}
# Can't use merge_samples on phyloseq here because some samples make up >1 merge

# Do manually on ASV table
asvtab.menu <- otu_table(ps.menu)@.Data
asvtab.menu.12 <- data.frame()

for (sample in seq(dim(samdf.protein)[1])){
     # Pull menu day -1
     one.before <- asvtab.menu[samdf.protein$delta1[sample], ]
     # Pull menu day -2
     two.before <- asvtab.menu[samdf.protein$delta2[sample], ]
     # Merge and place in new, aggregated OTU table
     asvtab.menu.12 <- rbind(asvtab.menu.12,
                             one.before + two.before)
     # Update food names (only has to be done once)
     if (sample == 1){names(asvtab.menu.12) <- names(one.before + two.before)}
     # Update sample name
     row.names(asvtab.menu.12)[sample] <- samdf.protein$row[sample]
}

# Now rebuild a subsetted phyloseq object
ps.menu.12 <- phyloseq(otu_table(asvtab.menu.12, taxa_are_rows = FALSE),
                       sample_data(ps.protein), # Now this matches
                       tax_table(ps.menu)) # Menu-specific taxonomy

# Remove any taxa that aren't present any longer
ps.menu.12 <- prune_taxa(taxa_sums(ps.menu.12) > 0, ps.menu.12)
ps.menu.12
```

## Visualize

First pass
```{r}
melt <- psmelt(ps.menu.12)
```

```{r}
ggplot(melt, aes(x = OTU, y = Sample, fill = Abundance>0)) +
     geom_tile() +
     scale_fill_manual(values = c('white', '#7e756d')) +
     theme(axis.text.y = element_blank(),
           axis.ticks.y = element_blank())
```

## Add dendrogram

### Samples
```{r}
# Run clustering
menu.dat <- as.matrix(ps.menu.12@otu_table@.Data)
# Make data binary:
menu.dat[menu.dat > 0] <- 1
menu.dendro <- 
     dist(menu.dat) %>% 
     hclust() %>% 
     as.dendrogram()

# Create dendro
dendro.plot.y <- ggdendrogram(data = menu.dendro, rotate = TRUE)

# Preview the plot
print(dendro.plot.y)
```

```{r}
# Re-order samples to match
menu.order <- order.dendrogram(menu.dendro)
menu.order

melt <- 
     mutate(melt,
            Sample = factor(Sample,
                            levels = row.names(menu.dat[menu.order, ])))
```

### Foods 

```{r}
# Run clustering
menu.dat <- as.matrix(ps.menu.12@otu_table@.Data)
# Make data binary:
menu.dat[menu.dat > 0] <- 1
menu.dendro <- 
     menu.dat %>% 
     t() %>% 
     dist() %>% 
     hclust() %>% 
     as.dendrogram()

# Create dendro
dendro.plot.x <- ggdendrogram(data = menu.dendro, rotate = FALSE)

# Preview the plot
print(dendro.plot.x)
```
```{r}
# Re-order samples to match
menu.order <- order.dendrogram(menu.dendro)
menu.order

melt <- 
     mutate(melt,
            OTU = factor(OTU,
                         levels = colnames(menu.dat[, menu.order])))
```

## Joint plot

```{r}
# Now, update original heatmap with these new levels
heatmap <- 
     ggplot(melt, aes(x = OTU, y = Sample, fill = Abundance>0)) +
     geom_tile() +
     scale_fill_manual(values = c('white', '#7e756d')) +
     coord_equal() +
     theme(axis.text.y = element_blank(),
           axis.ticks.y = element_blank(),
           axis.text.x = element_text(angle = 20, 
                                      hjust = 1),
           legend.position = 'none') 

heatmap
```

```{r}
plot_grid(dendro.plot.y,
          heatmap,
          aligh = 'v')
```

