---
title: "Specific food plots"
output: html_notebook
---

# R setup

```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = file.path(getwd(), '..'))
```

```{r libraries, echo=FALSE}
library(here) 
library(phyloseq) 
library(tidyverse) 
```

```{r}
colors.detection <- 
     c('#849db1', 
       '#fbb04e',
       '#7e756d')

names(colors.detection) <- 
     c('DNA',
       'Protein',
       'Menu')
```

```{r}
# Plotting themes
theme_set(theme_bw() +
               theme(
                    axis.text = element_text(size = 12),
                    axis.title.x = ggtext::element_markdown(size = 14,
                                                            face = 'bold'),
                    axis.title.y = ggtext::element_markdown(size = 14,
                                                            face = 'bold'),
                    legend.title = element_text(size = 12,
                                                face = 'bold'),
                    strip.text = element_text(size = 12,
                                              face = 'bold')
               )
)
```

# Read in data

## Taxon name mapping

```{r}
name.sync <- 
     here('data',
          'processed',
          'Naming discrepancies.xlsx') %>% 
     readxl::read_excel()

name.sync
```
## Sample dates

```{r}
samples <- 
     here('data',
          'metadata',
          'Sample collection times.csv') %>% 
     read_csv()

samples
```

## Metaproteomic phyloseq

```{r}
ps.protein <- 
     here('data', 
          'processed', 
          'phyloseq',
          'combined',
          'filtered',
          # 'ps_mp_1PUP_taxa.rds') %>% # >=1 protein unique peptide
          'ps_mp_1UP_taxa.rds') %>% # >=1 unique peptide
     readRDS()
          
ps.protein
```

## Menu data phyloseq

```{r}
ps.menu <- 
     here('data', 
          'processed', 
          'phyloseq',
          'combined',
          'filtered',
          'ps_menu.rds') %>% 
     readRDS()

ps.menu
```

## Metabarcoding phyloseq

```{r}
ps.mb.plant <- 
     here('data', 
          'processed', 
          'phyloseq',
          'combined',
          'filtered',
          'ps_mb_trnL.rds') %>% 
     readRDS()

ps.mb.plant
```

```{r}
ps.mb.animal <- 
     here('data', 
          'processed', 
          'phyloseq',
          'combined',
          'filtered',
          'ps_mb_12SV5.rds') %>% 
     readRDS()

ps.mb.plant
```

# Pre-process

## Samples

```{r}
samples$date <- as.Date(samples$date,
                        format = '%m/%d/%y')
```

```{r}
# Add detection for each so shading is done by facet, below
detection <- c('Menu', 'DNA', 'Protein')
subj <- unique(samples$subj)

samples <-
     expand.grid(detection = detection, 
                 subj = subj) %>% 
     right_join(samples) %>% 
     arrange(study, subj, date) %>% 
     select(subj:time, detection)

samples
```

## Dietary data

```{r}
melt.menu <- psmelt(ps.menu) 
melt.mb.plant <- psmelt(ps.mb.plant)
melt.mb.animal <- psmelt(ps.mb.animal)
melt.mp <- psmelt(ps.protein)
```

Add common name and group by dataset:

```{r}
melt.menu <- 
     melt.menu %>% 
     left_join(select(name.sync,
                      menu_taxa, common_name, taxon_index),
               by = c('OTU' = 'menu_taxa'))

melt.mb.animal <- 
     melt.mb.animal %>% 
     left_join(select(name.sync,
                      mb_taxa, common_name, taxon_index),
               by = c('OTU' = 'mb_taxa'))

melt.mb.plant <- 
     melt.mb.plant %>% 
     left_join(select(name.sync,
                      mb_taxa, common_name, taxon_index),
               by = c('OTU' = 'mb_taxa'))

melt.mp <- 
     melt.mp %>% 
     left_join(select(name.sync,
                      mp_taxa, common_name, taxon_index),
               by = c('OTU' = 'mp_taxa'))
```

```{r}
# Add dataset info to each melted object
melt.menu$detection <-  'Menu'
melt.mb.plant$detection <- 'DNA'
melt.mb.animal$detection <- 'DNA'
melt.mp$detection <- 'Protein'
```

```{r}
melts <- list(melt.menu,
              melt.mb.animal,
              melt.mb.plant,
              melt.mp)
```

```{r}
vs <- c('study',
        'subj', 
        'date',
        'detection', 
        'taxon_index',
        'common_name', 
        'Abundance') # Shared variables to pull from each phyloseq

lapply(melts, ncol)
melts <- lapply(melts, function(x){select(x, one_of(vs))})
lapply(melts, ncol)
```

```{r}
melt <- bind_rows(melts)
dim(melt)
rm(melts)
```

```{r}
melt$detection <- factor(melt$detection, 
                         levels = c('Menu',
                                    'DNA',
                                    'Protein'))
```

# Plot

## Select taxa

```{r}
taxa <- c('chicken', 'cattle', 'grains')
```

### All detections

```{r}
plotID <- paste(Sys.Date(), as.character(sample(000:999,1)), sep=".")

for (taxon in taxa){
     melt.filt <- filter(melt, common_name == taxon)
     
     ggplot(melt.filt, aes(x = date)) +
          geom_tile(data = samples, aes(x = date, 
                                        y = 0),
                    fill = 'gray90',
                    height = Inf) +
          geom_bar(aes(y = Abundance, fill = detection), stat = 'identity') +
          facet_grid(cols = vars(subj),
                     rows = vars(detection),
                     scales = 'free',
                     space = 'free_x') +
          scale_fill_manual(values = colors.detection) +
          labs(x = 'Date', y = 'Food abundance') +
          theme(axis.text.x = element_blank(),
                legend.position = 'none',
                panel.grid = element_blank())
     
     ggsave(here('results', 
                 'biomarkers', 
                 paste0(plotID, 
                        '_',
                        taxon,
                        ' detection by measure and sample.pdf')),
            height = 4)
}
```

### Protein only

```{r}
plotID <- paste(Sys.Date(), as.character(sample(000:999,1)), sep=".")

samples.filt <- filter(samples, detection != 'DNA')

for (taxon in taxa){
     melt.filt <- 
          filter(melt, common_name == taxon & detection != 'DNA')
     
     ggplot(melt.filt, aes(x = date)) +
          geom_tile(data = samples.filt, aes(x = date, 
                                             y = 0),
                    fill = 'gray90',
                    height = Inf) +
          geom_bar(aes(y = Abundance, fill = detection), stat = 'identity') +
          facet_grid(cols = vars(subj),
                     rows = vars(detection),
                     scales = 'free',
                     space = 'free_x') +
          scale_fill_manual(values = colors.detection) +
          labs(x = 'Date', y = 'Food abundance') +
          theme(axis.text.x = element_blank(),
                legend.position = 'none',
                panel.grid = element_blank())
     
     ggsave(here('results', 
                 'biomarkers', 
                 paste0(plotID, 
                        '_',
                        taxon,
                        ' detection by measure and sample.pdf')),
            height = 4)
}
```
